version: '3.8'

services:
  llm-service:
    build: ./llm_service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  test-service:
    build: ./test_service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - LLM_SERVICE_URL=http://llm-service:8000
    depends_on:
      - llm-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

